#include "tui/theme.hpp"

uint8_t uitheme::button::fore = 0x0b;
uint8_t uitheme::button::back = 0x03;

uint8_t uitheme::editbox::fore = 0x00;
uint8_t uitheme::editbox::back = 0x07;
uint8_t uitheme::editbox::selected_fore = 0x0b;
uint8_t uitheme::editbox::selected_back = 0x03;

uint8_t uitheme::label::fore = 0x07;

uint8_t uitheme::listbox::fore = 0x00;
uint8_t uitheme::listbox::back = 0x07;
uint8_t uitheme::listbox::selected_fore = 0x0b;
uint8_t uitheme::listbox::selected_back = 0x03;

uint8_t uitheme::scroll_bar::fore = 0x07;
uint8_t uitheme::scroll_bar::back = 0x00;

uint8_t uitheme::window::fore = 0x07;
uint8_t uitheme::window::back = 0x08;
uint8_t uitheme::window::caption_fore = 0x0f;
uint8_t uitheme::window::caption_back = 0x07;
